#ifndef ASN1_PARSER_TEST_SIMPLE_TYPES2_MSG_H_INCLUDED
#define ASN1_PARSER_TEST_SIMPLE_TYPES2_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.

Module test-simple-types2 comment
*/

// NOTE: The simple type 'Simple-types-2-type1' has been generated to a C bitfield type and is used directly in 'test-module'
// NOTE: The simple type 'Simple-types-2-type2' has been generated to a C bitfield type and is used directly in 'test-module'

#endif // ASN1_PARSER_TEST_SIMPLE_TYPES2_MSG_H_INCLUDED
