#ifndef ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

// NOTE: The simple type 'Percent' has been generated to a C builtin type and is used directly in 'main-module'
// NOTE: The simple type 'Float' has been generated to a C builtin type and is used directly in 'main-module'
// NOTE: The simple type 'Double' has been generated to a C builtin type and is used directly in 'main-module'
// NOTE: The simple type 'Uint3' has been generated to a C bitfield type and is used directly in 'main-module'
// NOTE: The simple type 'Uint16-t' has been generated to a C builtin type and is used directly in 'main-module'

#endif // ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED
