#ifndef ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>
#include "imported_module_msg.h"

typedef struct
{
  float number_0_100;
  float number_float;
  double number_double;
  uint8_t number_3_bit : 3;
  uint16_t number_16_bit;
} __attribute__((packed)) Sample_packet;

#endif // ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED
