#ifndef ASN1_PARSER_SAMPLE_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_SAMPLE_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>

typedef struct
{
  uint8_t number : 3;
} __attribute__((packed)) Sample_packet;

#endif // ASN1_PARSER_SAMPLE_MODULE_MSG_H_INCLUDED
