#ifndef ASN1_PARSER_MODULE_D_MSG_H_INCLUDED
#define ASN1_PARSER_MODULE_D_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

// NOTE: The simple type 'Module-d-type' has been generated to a C builtin type and is used directly in 'module-c'

#endif // ASN1_PARSER_MODULE_D_MSG_H_INCLUDED
