#ifndef ASN1_PARSER_MODULE_A_MSG_H_INCLUDED
#define ASN1_PARSER_MODULE_A_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include "module_b_msg.h"

typedef struct
{
  Module_b_type module_a_variable;
} __attribute__((packed)) Module_a_type;

#endif // ASN1_PARSER_MODULE_A_MSG_H_INCLUDED
