#ifndef ASN1_PARSER_MODULE_B_MSG_H_INCLUDED
#define ASN1_PARSER_MODULE_B_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include "module_c_msg.h"

typedef struct
{
  Module_c_type module_b_variable;
} __attribute__((packed)) Module_b_type;

#endif // ASN1_PARSER_MODULE_B_MSG_H_INCLUDED
