#ifndef ASN1_PARSER_MODULE_C_MSG_H_INCLUDED
#define ASN1_PARSER_MODULE_C_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>
#include "module_d_msg.h"

typedef struct
{
  uint16_t module_c_variable;
} __attribute__((packed)) Module_c_type;

#endif // ASN1_PARSER_MODULE_C_MSG_H_INCLUDED
