#ifndef ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

// NOTE: The simple type 'Number' has been generated to a C bitfield type and is used directly in 'main-module'

#endif // ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED
