#ifndef ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>
#include "imported_module_msg.h"

typedef struct
{
  uint8_t number : 3;
} __attribute__((packed)) Packet_main_packet;

#endif // ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED
