#ifndef ASN1_PARSER_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

// NOTE: The simple type 'Double' has been generated to a C builtin type and is used directly in 'module'

typedef struct
{
  double double_number;
} __attribute__((packed)) Packet;

#endif // ASN1_PARSER_MODULE_MSG_H_INCLUDED
