#ifndef ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>
// NOTE: The simple type 'Percent' has been generated to a C builtin type and is used directly in 'main-module'
// NOTE: The simple type 'Float' has been generated to a C builtin type and is used directly in 'main-module'
// NOTE: The simple type 'Double' has been generated to a C builtin type and is used directly in 'main-module'
// NOTE: The simple type 'Uint3' has been generated to a C bitfield type and is used directly in 'main-module'
// NOTE: The simple type 'Uint16-t' has been generated to a C builtin type and is used directly in 'main-module'

typedef struct
{
  float number_0_100;
  float number_float;
  double number_double;
  uint8_t number_3_bit : 3;
  uint16_t number_16_bit;
} __attribute__((packed)) Sample_packet;

#endif // ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED
