#ifndef ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>

typedef struct
{
  uint8_t imported_definition : 3;
} __attribute__((packed)) Imported_packet;

#endif // ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED
