#ifndef ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include "imported_module_msg.h"

typedef struct
{
  Imported_packet import;
} __attribute__((packed)) Packet;

#endif // ASN1_PARSER_MAIN_MODULE_MSG_H_INCLUDED
