#ifndef ASN1_PARSER_TEST_MODULE_DEPS_MSG_H_INCLUDED
#define ASN1_PARSER_TEST_MODULE_DEPS_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>
// NOTE: The simple type 'Type211' has been generated to a C bitfield type and is used directly in 'test-module-deps'
// NOTE: The simple type 'Type212' has been generated to a C bitfield type and is used directly in 'test-module-deps'
// NOTE: The simple type 'Type221' has been generated to a C bitfield type and is used directly in 'test-module-deps'
// NOTE: The simple type 'Type222' has been generated to a C bitfield type and is used directly in 'test-module-deps'

typedef struct
{
  uint8_t field1 : 4;
  uint8_t field2 : 4;
} __attribute__((packed)) Type_seq_21;

typedef struct
{
  uint8_t field1 : 4;
  uint8_t field2 : 4;
} __attribute__((packed)) Type_seq_22;

typedef struct
{
  Type_seq_21 field1;
  Type_seq_22 field2;
} __attribute__((packed)) Test_seq_3;

#endif // ASN1_PARSER_TEST_MODULE_DEPS_MSG_H_INCLUDED
