#ifndef ASN1_PARSER_MODULE1_MSG_H_INCLUDED
#define ASN1_PARSER_MODULE1_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include "cfe_headers_msg.h"

typedef struct
{
  Cfe_tlm_header header;
} __attribute__((packed)) Packet1;

#endif // ASN1_PARSER_MODULE1_MSG_H_INCLUDED
