#ifndef ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED
#define ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>

typedef struct
{
  uint8_t imported_definition1 : 3;
} __attribute__((packed)) Imported_packet1;

typedef struct
{
  uint16_t imported_definition2 : 11;
} __attribute__((packed)) Imported_packet2;

#endif // ASN1_PARSER_IMPORTED_MODULE_MSG_H_INCLUDED
