#ifndef ASN1_PARSER_MODULE2_MSG_H_INCLUDED
#define ASN1_PARSER_MODULE2_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include "imported_module_msg.h"

typedef struct
{
  Imported_packet2 import;
} __attribute__((packed)) Packet2;

#endif // ASN1_PARSER_MODULE2_MSG_H_INCLUDED
