#ifndef ASN1_PARSER_CCSDS_HEADERS_MSG_H_INCLUDED
#define ASN1_PARSER_CCSDS_HEADERS_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.

CCSDS TM/TC headers
*/

#include <stdint.h>
#include "simple_types_msg.h"

typedef struct
{
  // moved from Ccsds-primary-header to here to avoid C compiler padding issues
  uint8_t packet_version_number : 3;
  uint8_t packet_type_is_cmd : 1;
  uint8_t sec_hdr_flag_is_present : 1;
  uint16_t application_process_identifier : 11;
} __attribute__((packed)) Packet_identification;

typedef enum {
  continuation_packet_in_sequence = 0,
  first_packet_in_sequence = 1,
  last_packet_in_sequence = 2,
  complete_packet = 3,
} __attribute__((packed)) Sequence_flag;

typedef struct
{
  uint16_t subsystem;
  uint16_t system_id;
} __attribute__((packed)) Ccsds_extended_header;

typedef struct
{
  Sequence_flag sequence_flags : 2;
  uint16_t packet_sequence_count : 14;
} __attribute__((packed)) Packet_sequence_control;

/* primary header */
typedef struct
{
  Packet_identification packet_identification;
  Packet_sequence_control packet_sequence_control;
  // length of the packet
  uint16_t packet_data_length;
} __attribute__((packed)) Ccsds_primary_header;

#endif // ASN1_PARSER_CCSDS_HEADERS_MSG_H_INCLUDED
