#ifndef ASN1_PARSER_CFE_HEADERS_MSG_H_INCLUDED
#define ASN1_PARSER_CFE_HEADERS_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.

cFE TM/TC headers
*/

#include <stdint.h>
#include "simple_types_msg.h"
#include "ccsds_headers_msg.h"

typedef struct
{
  uint8_t function_code;
  uint8_t checksum;
} __attribute__((packed)) Cfe_tc_secondary_header;

typedef struct
{
  // [sec]
  uint32_t seconds;
  // unit: 2**-16 sec = 0.015 ms
  uint16_t subsecs;
} __attribute__((packed)) Cfe_tm_secondary_header;

typedef struct
{
  Ccsds_primary_header primary;
  Cfe_tc_secondary_header secondary;
} __attribute__((packed)) Cfe_cmd_header;

typedef struct
{
  Ccsds_primary_header primary;
  Cfe_tm_secondary_header secondary;
  // Spares
  uint32_t spare;
} __attribute__((packed)) Cfe_tlm_header;

#endif // ASN1_PARSER_CFE_HEADERS_MSG_H_INCLUDED
