#ifndef ASN1_PARSER_SANDBOX_HK_PC_MSG_H_INCLUDED
#define ASN1_PARSER_SANDBOX_HK_PC_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>
#include "cfe_headers_msg.h"
#include "simple_types_msg.h"
// NOTE: The simple type 'Percent-range' has been generated to a C builtin type and is used directly in 'sandbox-hk-pc'
// NOTE: The simple type 'Load-range' has been generated to a C builtin type and is used directly in 'sandbox-hk-pc'

typedef struct
{
  // [%] CPU usage
  float cpu;
  // load from 1 minute average
  float load1;
  // load from 5 minutes average
  float load5;
  // load from 15 minutes average
  float load15;
  // [byte] total RAM
  uint64_t total_ram;
  // [byte] free RAM
  uint64_t free_ram;
  // [byte] free SWAP
  uint64_t free_swap;
} __attribute__((packed)) Payload_sandbox_hk_pc;

/* (0x0899) SANDBOX PC housekeeping telemetry */
typedef struct
{
  Cfe_tlm_header header;
  Payload_sandbox_hk_pc payload;
} __attribute__((packed)) Sandbox_hk_pc;

#endif // ASN1_PARSER_SANDBOX_HK_PC_MSG_H_INCLUDED
