#ifndef ASN1_PARSER_SIMPLE_TYPES_MSG_H_INCLUDED
#define ASN1_PARSER_SIMPLE_TYPES_MSG_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

// NOTE: The simple type 'Uint3' has been generated to a C bitfield type and is used directly in 'ccsds-headers'
// NOTE: The simple type 'Uint11' has been generated to a C bitfield type and is used directly in 'ccsds-headers'
// NOTE: The simple type 'Uint14' has been generated to a C bitfield type and is used directly in 'ccsds-headers'
// NOTE: The simple type 'Uint8-t' has been generated to a C builtin type and is used directly in 'cfe-headers'
// NOTE: The simple type 'Uint16-t' has been generated to a C builtin type and is used directly in 'ccsds-headers', 'cfe-headers'
// NOTE: The simple type 'Uint32-t' has been generated to a C builtin type and is used directly in 'cfe-headers'
// NOTE: The simple type 'Uint64-t' has been generated to a C builtin type and is used directly in 'sandbox-hk-pc'

#endif // ASN1_PARSER_SIMPLE_TYPES_MSG_H_INCLUDED
