/*
This file was autogenerated from ASN.1 model.
*/

#include "sample_module.h"

Sample_packet sample_packet = {
  .sample_packet_with_component = {
    .with_component_packet_number_1 = 23,
    .with_component_packet_number_2 = 42,
    .with_component_packet_inner_with_component = {
      .inner_with_component_packet_number_1 = 1,
      .inner_with_component_packet_number_2 = 9,
    },
    .with_component_packet_bool = 1,
  },
};
