#ifndef ASN1_PARSER_SAMPLE_MODULE_H_INCLUDED
#define ASN1_PARSER_SAMPLE_MODULE_H_INCLUDED

/*
This file was autogenerated from ASN.1 model.
*/

#include <stdint.h>

typedef struct
{
  uint8_t inner_with_component_packet_number_1;
  uint16_t inner_with_component_packet_number_2;
} __attribute__((packed)) Inner_with_component_packet;

typedef struct
{
  uint32_t with_component_packet_number_1;
  uint64_t with_component_packet_number_2;
  Inner_with_component_packet with_component_packet_inner_with_component;
  uint8_t with_component_packet_bool : 1;
} __attribute__((packed)) With_component_packet;

typedef struct
{
  uint8_t sample_packet_uint_number;
  With_component_packet sample_packet_with_component;
} __attribute__((packed)) Sample_packet;

Sample_packet sample_packet;

#endif // ASN1_PARSER_SAMPLE_MODULE_H_INCLUDED
